## Linear Regression Using PyTorch

In [152]:
import torch

#### From Scratch using Gradient Descent (No bias)

In [153]:
# independent variable

x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
x

tensor([1., 2., 3., 4.])

In [154]:
# dependent variable

y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)
y

tensor([2., 4., 6., 8.])

In [155]:
# weights

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
w

tensor(0., requires_grad=True)

In [156]:
# forward pass / forward propogation (gives y_hat)

def get_forward_pass(x_val):
    return(w * x_val)   #y_hat

In [157]:
# loss function

def get_loss(y_val, y_hat):
    return((y_hat - y_val)**2).mean()

In [158]:
# Training 

learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    y_pred = get_forward_pass(x)  # y_predicted
    l = get_loss(y, y_pred)       # loss
    l.backward()                  # backward pass/ propogation (gives gradient descent)
    with torch.no_grad():         # update weights
        w -= learning_rate * w.grad
    w.grad.zero_()                 # updating gradients to zero
    
    if epoch % 10 == 0:
        print(f'epoch{epoch+1}: w= {w:.3f},loss= {l:.8f}') 

epoch1: w= 0.300,loss= 30.00000000
epoch11: w= 1.665,loss= 1.16278565
epoch21: w= 1.934,loss= 0.04506890
epoch31: w= 1.987,loss= 0.00174685
epoch41: w= 1.997,loss= 0.00006770
epoch51: w= 1.999,loss= 0.00000262
epoch61: w= 2.000,loss= 0.00000010
epoch71: w= 2.000,loss= 0.00000000
epoch81: w= 2.000,loss= 0.00000000
epoch91: w= 2.000,loss= 0.00000000


#### Linear Regression uisng Neural Networks

In [159]:
import torch.nn as nn
import pandas as pd

In [160]:
df = pd.read_csv('Salary_dataset.csv')
df.head()

Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [161]:
del df['Unnamed: 0']

In [162]:
df.head()

YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [163]:
df_tensor = torch.tensor(df.values)

In [164]:
df_tensor

tensor([[1.2000e+00, 3.9344e+04],
        [1.4000e+00, 4.6206e+04],
        [1.6000e+00, 3.7732e+04],
        [2.1000e+00, 4.3526e+04],
        [2.3000e+00, 3.9892e+04],
        [3.0000e+00, 5.6643e+04],
        [3.1000e+00, 6.0151e+04],
        [3.3000e+00, 5.4446e+04],
        [3.3000e+00, 6.4446e+04],
        [3.8000e+00, 5.7190e+04],
        [4.0000e+00, 6.3219e+04],
        [4.1000e+00, 5.5795e+04],
        [4.1000e+00, 5.6958e+04],
        [4.2000e+00, 5.7082e+04],
        [4.6000e+00, 6.1112e+04],
        [5.0000e+00, 6.7939e+04],
        [5.2000e+00, 6.6030e+04],
        [5.4000e+00, 8.3089e+04],
        [6.0000e+00, 8.1364e+04],
        [6.1000e+00, 9.3941e+04],
        [6.9000e+00, 9.1739e+04],
        [7.2000e+00, 9.8274e+04],
        [8.0000e+00, 1.0130e+05],
        [8.3000e+00, 1.1381e+05],
        [8.8000e+00, 1.0943e+05],
        [9.1000e+00, 1.0558e+05],
        [9.6000e+00, 1.1697e+05],
        [9.7000e+00, 1.1264e+05],
        [1.0400e+01, 1.2239e+05],
        [1.060

In [165]:
X = df_tensor[:,0]
X = X.view(X.shape[0],1)
Y = df_tensor[:,1]


In [166]:
input_size = 1
output_size = 1

In [167]:
model = nn.Linear(input_size, output_size)

In [168]:
criterion = nn.MSELoss()

In [169]:
lr = 0.01
optimize = torch.optim.SGD(model.parameters(), lr=lr)

In [170]:
n_epochs = 100
for epoch in range(n_epochs):
    y_predicted = model(X)
    loss = criterion(Y, y_predicted)
    loss.backward()
    optimze.step()
    optimize.zero_grad()
    if epoch % 10 == 0:
        print(f'epoch{epoch+1}: w= {w:.3f},loss= {l:.8f}') 

RuntimeError: mat1 and mat2 must have the same dtype