## Basics of PyTorch

In [2]:
import torch

In [ ]:
# Creating an empty tensor
# tensor is like an array in numpy

In [10]:
x1 = torch.empty(1)     #1-D
x1

tensor([2.3694e-38])

In [9]:
x2 = torch.empty(2, 3)   #2-D
x2

tensor([[1.3553e-19, 1.3563e-19, 1.3320e+31],
        [1.1869e+27, 6.6741e+22, 7.0373e+22]])

In [11]:
# Creating a tensor with random number

In [12]:
x3 = torch.rand(2,2)
x3

tensor([[0.1973, 0.2637],
        [0.3348, 0.2737]])

In [13]:
# Creating tensors with zeros and ones just like Numpy functions

In [14]:
x4 = torch.zeros(2, 3)
x4

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x5 = torch.ones(2, 3, dtype=torch.int)  # integer values instead of float
x5

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [18]:
print('data_type:', x5.dtype)
print('data_size:', x5.size())

data_type: torch.int32
data_size: torch.Size([2, 3])


In [19]:
# Addition 

In [20]:
x4 + x5

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
torch.add(x4, x5)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
y1 = torch.rand(2,2)   #updates value of y1 
y1.add_(x3)

tensor([[0.6043, 0.7293],
        [0.4840, 0.6012]])

In [ ]:
# Subtraction

In [24]:
y1 - x3

tensor([[0.4070, 0.4656],
        [0.1492, 0.3275]])

In [25]:
y1.sub(x3)

tensor([[0.4070, 0.4656],
        [0.1492, 0.3275]])

In [26]:
# Multiplication

In [27]:
y1.mul(x3)

tensor([[0.1193, 0.1923],
        [0.1621, 0.1646]])

In [28]:
y1 * x3

tensor([[0.1193, 0.1923],
        [0.1621, 0.1646]])

In [ ]:
# Division

In [29]:
y1 / x3

tensor([[3.0624, 2.7657],
        [1.4458, 2.1965]])

In [30]:
y1.div(x3)

tensor([[3.0624, 2.7657],
        [1.4458, 2.1965]])

In [31]:
# Reshaping 

In [32]:
x6 = torch.rand(4, 4)

In [33]:
y2 = x6.view(16)
y2

tensor([0.6389, 0.7324, 0.6216, 0.1218, 0.7908, 0.5509, 0.0808, 0.4795, 0.2717,
        0.7179, 0.7074, 0.8134, 0.7330, 0.1964, 0.6378, 0.1119])

In [34]:
y3 = x6.view(-1, 8)
y3

tensor([[0.6389, 0.7324, 0.6216, 0.1218, 0.7908, 0.5509, 0.0808, 0.4795],
        [0.2717, 0.7179, 0.7074, 0.8134, 0.7330, 0.1964, 0.6378, 0.1119]])

In [35]:
# PyTorch to Numpy and Vice-Versa

In [36]:
import numpy as np

In [38]:
a1 = torch.ones(5)
a1

tensor([1., 1., 1., 1., 1.])

In [39]:
a1.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [40]:
a2 = np.ones(5)
a2

array([1., 1., 1., 1., 1.])

In [41]:
torch.from_numpy(a2)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [42]:
# Gradient Descent / Autograd

In [49]:
a3 = torch.rand(3, requires_grad=True)    #requires_grad=True is important for Grad functions
a3

tensor([0.5162, 0.7293, 0.3558], requires_grad=True)

In [50]:
b1 = a3 + 2    # forward pass

In [51]:
b1

tensor([2.5162, 2.7293, 2.3558], grad_fn=<AddBackward0>)

In [52]:
c1 = b1*b1*2
c1

tensor([12.6628, 14.8979, 11.0997], grad_fn=<MulBackward0>)

In [53]:
c1 = c1.mean()
c1

tensor(12.8868, grad_fn=<MeanBackward0>)

In [54]:
c1.backward()      #uses Jacobian Matrix
print(a3.grad)

tensor([3.3550, 3.6390, 3.1411])


In [55]:
# If Gradient Function is not needed in the codes ahead:

In [56]:
a3.requires_grad_(False)
a3

tensor([0.5162, 0.7293, 0.3558])

In [57]:
c2 = a3.detach()
c2

tensor([0.5162, 0.7293, 0.3558])

In [58]:
with torch.no_grad():
    c3 = a3 + 2
    print(c3)

tensor([2.5162, 2.7293, 2.3558])
